### ISSUE TITLE
Update unit tests switching enzyme to react-testing-library

### ISSUE THREAD

**Issue by netojose** [netojose/react-modal#54]
*enzyme* is not maintained anymore, and should to be replaced by r*eact-testing-library*

**Comment by griseduardo** [comment]
Hello, I would like work in this issue, can you assign me?

**Comment by netojose** [comment]
Hi @griseduardo , thanks for your interest. Of course!

**Comment by netojose** [comment]
Amazing job, @griseduardo , the new testing library was replaced, and the code coverage continue good, and everything passing.

Thanks a lot!!!!

<img width="737" alt="Screenshot 2023-10-23 at 18 14 40" src="https://github.com/netojose/react-modal/assets/134008/8eaae38a-4531-416d-908f-5a0ca096885e">


I already merged and this issue it's closed :)
